### ISSUE TITLE
Error: [E892] Unknown function registry: 'vectors'.

### ISSUE THREAD

**Issue by jordanbr20** [raga70/FullyAutomatedRedditVideoMakerBot#1]
First, I am glad to see someone is keeping this alive! :) Thank you!

*** FRESH INSTALL 1ST RUN ***
Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the
Discord community.
Version: 3.3.0
Error: [E892] Unknown function registry: 'vectors'.

Available names: architectures, augmenters, batchers, callbacks, cli, datasets, displacy_colors, factories,
initializers, languages, layers, lemmatizers, loggers, lookups, losses, misc, models, ops, optimizers, readers,
schedules, scorers, tokenizers
Config: {'allow_nsfw': False, 'theme': 'transparent', 'times_to_run': 1, 'opacity': 0.9, 'storymode': True,
'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1,
'channel_name': 'REDACTED', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',
'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,
'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,
'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True,
'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',
'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':
'1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\main.py", line 48, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\reddit\subreddit.py", line 127, in get_subreddit_threads
    content["thread_post"] = posttextparser(submission.selftext)
  File "C:\Users\USER\Desktop\FullyAutomatedRedditVideoMakerBot\utils\posttextparser.py", line 16, in posttextparser
    nlp = spacy.load("en_core_web_sm")
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\__init__.py", line 54, in load
    return util.load_model(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 442, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 478, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\en_core_web_sm\__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 659, in load_model_from_init_py
    return load_model_from_path(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 516, in load_model_from_path
    nlp = load_model_from_config(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 564, in load_model_from_config
    nlp = lang_cls.from_config(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\language.py", line 1749, in from_config
    resolved_nlp = registry.resolve(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\confection\__init__.py", line 760, in resolve
    resolved, _ = cls._make(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\confection\__init__.py", line 809, in _make
    filled, _, resolved = cls._fill(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\confection\__init__.py", line 863, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\confection\__init__.py", line 1069, in make_promise_schema
    func = cls.get(reg_name, func_name)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 128, in get
    raise RegistryError(Errors.E892.format(name=registry_name, available=names))
catalogue.RegistryError: [E892] Unknown function registry: 'vectors'.

Available names: architectures, augmenters, batchers, callbacks, cli, datasets, displacy_colors, factories, initializers, languages, layers, lemmatizers, loggers, lookups, losses, misc, models, ops, optimizers, readers, schedules, scorers, tokenizers

**Comment by jordanbr20** [comment]
Removal and reinstall fixed this issue.
